version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44352:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./calculo-cdb
      dockerfile: Dockerfile
    ports:
      - "4200:80" 
    depends_on:
      - api  
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
